### ISSUE TITLE
Nodemon seems to not fire my shutdown function

### ISSUE THREAD

**Issue by m00nwtchr** [jtlapp/node-cleanup#12]

**Comment by jtlapp** [comment]
[According to this `nodemon` issue](https://github.com/remy/nodemon/issues/33), `nodemon` does not appear to give child processes a chance to handle signals. Nothing either of us can do about it but go fix `nodemon`.

**Comment by m00nwtchr** [comment]
hmm k

**Comment by m00nwtchr** [comment]
hmm maybe you could fix this by doing what they suggest in here? https://github.com/remy/nodemon/blob/master/README.md#controlling-shutdown-of-your-script

**Comment by jtlapp** [comment]
Good find, but `SIGUSR2` isn't a shutdown signal. An application receiving it could do anything it wants and need not shut down. So `node-cleanup` can't shutdown upon detecting it.

You might implement that yourself in your app. It's kinda weird that an app would need to implement a special shutdown process just to run properly under `nodemon`.

**Comment by m00nwtchr** [comment]
true.. maybe there's a way to figure out if you are running under node mon and use that event only in such a case?
